export const products = [
  {
    name: "Arduino Uno R3",
    image: "/src/assets/images/arduino.png",
    description:
      "Microcontroller board based on the ATmega328P. It features 14 digital input/output pins (of which 6 can be used as PWM outputs), 6 analog inputs, a 16 MHz quartz crystal, a USB connection, a power jack, an ICSP header, and a reset button.",
    brand: "Arduino",
    category: "Microcontroller",
    price: 1000,
    countInStock: 100,
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "Raspberry Pi 4 Model B",
    image: "/src/assets/images/raspberry-pi.jpeg",
    description:
      "A small, powerful computer featuring a quad-core 64-bit processor, dual-display support at resolutions up to 4K, USB 3.0, Bluetooth 5.0, Gigabit Ethernet, and 2GB, 4GB, or 8GB of RAM.",
    brand: "Raspberry Pi",
    category: "Single-board Computer",
    price: 3500,
    countInStock: 50,
    rating: 4.8,
    numReviews: 18,
  },
  {
    name: "ESP8266 NodeMCU",
    image: "/src/assets/images/esp32.jpg",
    description:
      "A low-cost Wi-Fi microchip with full TCP/IP stack and microcontroller capability. Ideal for IoT projects for controlling devices over the Internet.",
    brand: "Espressif Systems",
    category: "Microcontroller with Wi-Fi",
    price: 500,
    countInStock: 200,
    rating: 3.3,
    numReviews: 20,
  },
  {
    name: "DHT22 Temperature and Humidity Sensor",
    image: "/src/assets/images/servo-motor.jpeg",
    description:
      "A reliable sensor for measuring temperature and humidity. It provides accurate readings and has a wide measuring range, making it suitable for various applications.",
    brand: "Adafruit",
    category: "Sensor",
    price: 250,
    countInStock: 150,
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: "HC-SR04 Ultrasonic Sensor",
    image: "/src/assets/images/esp32.jpg",
    description:
      "An ultrasonic sensor that measures distance by emitting ultrasonic waves and measuring the time it takes for the echo to return. Ideal for obstacle avoidance in robotics.",
    brand: "Generic",
    category: "Sensor",
    price: 150,
    countInStock: 100,
    rating: 3.2,
    numReviews: 10,
  },
  {
    name: "MQ-2 Gas Sensor",
    image: "/src/assets/images/raspberry-pi.jpeg",
    description:
      "A gas sensor capable of detecting various combustible gases, including LPG, hydrogen, and methane, in the air. Suitable for safety and environmental monitoring.",
    brand: "Generic",
    category: "Sensor",
    price: 300,
    countInStock: 120,
    rating: 4.0,
    numReviews: 8,
  },
  {
    name: "NEO-6M GPS Module",
    image: "/src/assets/images/raspb-4.png",
    description:
      "A compact GPS module capable of providing accurate geographical positioning. Features include high sensitivity, low power consumption, and a built-in antenna.",
    brand: "U-blox",
    category: "Module",
    price: 1200,
    countInStock: 80,
    rating: 3,
    numReviews: 14,
  },
  {
    name: "BMP280 Barometric Pressure Sensor",
    image: "/src/assets/images/servo-motor.jpeg",
    description:
      "A digital barometric pressure and temperature sensor that is ideal for weather stations, indoor navigation, and fitness applications.",
    brand: "Bosch",
    category: "Sensor",
    price: 400,
    countInStock: 150,
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "RFID RC522 Reader/Writer",
    image: "/src/assets/images/arduino.png",
    description:
      "A reader/writer module for RFID tags. It operates at 13.56 MHz and can be used for access control, payment systems, and identification.",
    brand: "Generic",
    category: "Module",
    price: 450,
    countInStock: 110,
    rating: 4.1,
    numReviews: 9,
  },
  {
    name: "L298N Motor Driver",
    image: "/src/assets/images/servo-motor.jpeg",
    description:
      "A high-power motor driver module capable of driving up to two DC motors. Features include support for up to 2A per channel, thermal protection, and easy interfacing.",
    brand: "Generic",
    category: "Module",
    price: 350,
    countInStock: 90,
    rating: 4.4,
    numReviews: 11,
  },
];
